### ISSUE TITLE
Code_deploy cookbook is failing and stopping the codedeploy-agent

### ISSUE THREAD

**Issue by vijaypatnana** [meringu/code_deploy#9]
Hi,

I am running chef-client on a server to install and start codedeploy agent, suddenly it started failing with this error and stopping the agent aswell. can anyone help me on this? Thanks
```
[2018-06-20 12:02:36.865] [d-48VU0RRTT][stdout][2018-06-20T12:02:36-04:00] INFO: Processing yum_package[/var/chef/cache/code_deploy/codedeploy-agent-1.0-1.1518.noarch.rpm] action install (/var/chef/cache/cookbooks/code_deploy/resources/agent_rhel.rb line 19)
[2018-06-20 12:18:02.876] [d-48VU0RRTT][stdout][0m
[2018-06-20 12:18:02.876] [d-48VU0RRTT][stdout]================================================================================[0m
[2018-06-20 12:18:02.876] [d-48VU0RRTT][stdout][31mError executing action `install` on resource 'yum_package[/var/chef/cache/code_deploy/codedeploy-agent-1.0-1.1518.noarch.rpm]'[0m
[2018-06-20 12:18:02.876] [d-48VU0RRTT][stdout]================================================================================[0m
[2018-06-20 12:18:02.876] [d-48VU0RRTT][stdout]
[2018-06-20 12:18:02.876] [d-48VU0RRTT][stdout][0mMixlib::ShellOut::CommandTimeout[0m
[2018-06-20 12:18:02.876] [d-48VU0RRTT][stdout]--------------------------------[0m
[2018-06-20 12:18:02.876] [d-48VU0RRTT][stdout]Command timed out after 900s:
[2018-06-20 12:18:02.876] [d-48VU0RRTT][stdout][0mCommand exceeded allowed execution time, process terminated
[2018-06-20 12:18:02.876] [d-48VU0RRTT][stdout][0m---- Begin output of yum -d0 -e0 -y localinstall /var/chef/cache/code_deploy/codedeploy-agent-1.0-1.1518.noarch.rpm ----
[2018-06-20 12:18:02.876] [d-48VU0RRTT][stdout][0mSTDOUT: pre hook : 2
[2018-06-20 12:18:02.877] [d-48VU0RRTT][stdout][0mChecking the ruby version.
[2018-06-20 12:18:02.877] [d-48VU0RRTT][stdout][0mStop the running codedeploy-agent in the pre hook.
[2018-06-20 12:18:02.877] [d-48VU0RRTT][stdout][0mStopping codedeploy-agent:error: %pre(codedeploy-agent-1.0-1.1518.noarch) scriptlet failed, signal 15
[2018-06-20 12:18:02.877] [d-48VU0RRTT][stdout][0mSTDERR: Error in PREIN scriptlet in rpm package codedeploy-agent-1.0-1.1518.noarch
[2018-06-20 12:18:02.877] [d-48VU0RRTT][stdout][0m---- End output of yum -d0 -e0 -y localinstall /var/chef/cache/code_deploy/codedeploy-agent-1.0-1.1518.noarch.rpm ----
[2018-06-20 12:18:02.877] [d-48VU0RRTT][stdout][0mRan yum -d0 -e0 -y localinstall /var/chef/cache/code_deploy/codedeploy-agent-1.0-1.1518.noarch.rpm returned 1[0m
[2018-06-20 12:18:02.877] [d-48VU0RRTT][stdout]
[2018-06-20 12:18:02.877] [d-48VU0RRTT][stdout][0mResource Declaration:[0m
[2018-06-20 12:18:02.877] [d-48VU0RRTT][stdout]---------------------[0m
[2018-06-20 12:18:02.877] [d-48VU0RRTT][stdout]# In /var/chef/cache/cookbooks/code_deploy/resources/agent_rhel.rb
[2018-06-20 12:18:02.877] [d-48VU0RRTT][stdout][0m
[2018-06-20 12:18:02.877] [d-48VU0RRTT][stdout][0m 19: package installer_cache_path('rpm')
[2018-06-20 12:18:02.877] [d-48VU0RRTT][stdout][0m 20:
[2018-06-20 12:18:02.877] [d-48VU0RRTT][stdout][0m
[2018-06-20 12:18:02.877] [d-48VU0RRTT][stdout][0mCompiled Resource:[0m
[2018-06-20 12:18:02.877] [d-48VU0RRTT][stdout]------------------[0m
[2018-06-20 12:18:02.877] [d-48VU0RRTT][stdout]# Declared in /var/chef/cache/cookbooks/code_deploy/resources/agent_rhel.rb:19:in `block in class_from_file'
[2018-06-20 12:18:02.877] [d-48VU0RRTT][stdout][0m
[2018-06-20 12:18:02.877] [d-48VU0RRTT][stdout][0myum_package("/var/chef/cache/code_deploy/codedeploy-agent-1.0-1.1518.noarch.rpm") do
[2018-06-20 12:18:02.877] [d-48VU0RRTT][stdout][0m package_name "/var/chef/cache/code_deploy/codedeploy-agent-1.0-1.1518.noarch.rpm"
[2018-06-20 12:18:02.877] [d-48VU0RRTT][stdout][0m action [:install]
[2018-06-20 12:18:02.877] [d-48VU0RRTT][stdout][0m retries 0
[2018-06-20 12:18:02.877] [d-48VU0RRTT][stdout][0m retry_delay 2
[2018-06-20 12:18:02.877] [d-48VU0RRTT][stdout][0m default_guard_interpreter :default
[2018-06-20 12:18:02.877] [d-48VU0RRTT][stdout][0m declared_type :package
[2018-06-20 12:18:02.878] [d-48VU0RRTT][stdout][0m cookbook_name "code_deploy"
[2018-06-20 12:18:02.878] [d-48VU0RRTT][stdout][0m flush_cache {:before=>false, :after=>false}
[2018-06-20 12:18:02.878] [d-48VU0RRTT][stdout][0m version "1.0-1.1518"
[2018-06-20 12:18:02.878] [d-48VU0RRTT][stdout][0m source "/var/chef/cache/code_deploy/codedeploy-agent-1.0-1.1518.noarch.rpm"
[2018-06-20 12:18:02.878] [d-48VU0RRTT][stdout][0mend
[2018-06-20 12:18:02.878] [d-48VU0RRTT][stdout][0m
[2018-06-20 12:18:02.878] [d-48VU0RRTT][stdout][0mPlatform:[0m
[2018-06-20 12:18:02.878] [d-48VU0RRTT][stdout]---------[0m
[2018-06-20 12:18:02.878] [d-48VU0RRTT][stdout]x86_64-linux[0m
[2018-06-20 12:18:02.878] [d-48VU0RRTT][stdout]
[2018-06-20 12:18:02.878] [d-48VU0RRTT][stdout][0m[2018-06-20T12:18:02-04:00] INFO: Running queued delayed notifications before re-raising exception
[2018-06-20 12:18:02.878] [d-48VU0RRTT][stdout][0m
[2018-06-20 12:18:02.878] [d-48VU0RRTT][stdout]================================================================================[0m
[2018-06-20 12:18:02.878] [d-48VU0RRTT][stdout][31mError executing action `install` on resource 'code_deploy_agent[codedeploy-agent]'[0m
[2018-06-20 12:18:02.878] [d-48VU0RRTT][stdout]================================================================================[0m
[2018-06-20 12:18:02.878] [d-48VU0RRTT][stdout]
[2018-06-20 12:18:02.878] [d-48VU0RRTT][stdout][0mMixlib::ShellOut::CommandTimeout[0m
[2018-06-20 12:18:02.878] [d-48VU0RRTT][stdout]--------------------------------[0m
[2018-06-20 12:18:02.878] [d-48VU0RRTT][stdout]yum_package[/var/chef/cache/code_deploy/codedeploy-agent-1.0-1.1518.noarch.rpm] (/var/chef/cache/cookbooks/code_deploy/resources/agent_rhel.rb line 19) had an error: Mixlib::ShellOut::CommandTimeout: Command timed out after 900s:
[2018-06-20 12:18:02.878] [d-48VU0RRTT][stdout][0mCommand exceeded allowed execution time, process terminated
[2018-06-20 12:18:02.878] [d-48VU0RRTT][stdout][0m---- Begin output of yum -d0 -e0 -y localinstall /var/chef/cache/code_deploy/codedeploy-agent-1.0-1.1518.noarch.rpm ----
[2018-06-20 12:18:02.878] [d-48VU0RRTT][stdout][0mSTDOUT: pre hook : 2
[2018-06-20 12:18:02.878] [d-48VU0RRTT][stdout][0mChecking the ruby version.
[2018-06-20 12:18:02.878] [d-48VU0RRTT][stdout][0mStop the running codedeploy-agent in the pre hook.
[2018-06-20 12:18:02.878] [d-48VU0RRTT][stdout][0mStopping codedeploy-agent:error: %pre(codedeploy-agent-1.0-1.1518.noarch) scriptlet failed, signal 15
[2018-06-20 12:18:02.878] [d-48VU0RRTT][stdout][0mSTDERR: Error in PREIN scriptlet in rpm package codedeploy-agent-1.0-1.1518.noarch
[2018-06-20 12:18:02.879] [d-48VU0RRTT][stdout][0m---- End output of yum -d0 -e0 -y localinstall /var/chef/cache/code_deploy/codedeploy-agent-1.0-1.1518.noarch.rpm ----
[2018-06-20 12:18:02.879] [d-48VU0RRTT][stdout][0mRan yum -d0 -e0 -y localinstall /var/chef/cache/code_deploy/codedeploy-agent-1.0-1.1518.noarch.rpm returned 1[0m
[2018-06-20 12:18:02.879] [d-48VU0RRTT][stdout]
[2018-06-20 12:18:02.879] [d-48VU0RRTT][stdout][0mResource Declaration:[0m
[2018-06-20 12:18:02.879] [d-48VU0RRTT][stdout]---------------------[0m
[2018-06-20 12:18:02.879] [d-48VU0RRTT][stdout]# In /var/chef/cache/cookbooks/code_deploy/recipes/default.rb
[2018-06-20 12:18:02.879] [d-48VU0RRTT][stdout][0m
[2018-06-20 12:18:02.879] [d-48VU0RRTT][stdout][0m 1: code_deploy_agent 'codedeploy-agent'
[2018-06-20 12:18:02.879] [d-48VU0RRTT][stdout][0m
[2018-06-20 12:18:02.879] [d-48VU0RRTT][stdout][0mCompiled Resource:[0m
[2018-06-20 12:18:02.879] [d-48VU0RRTT][stdout]------------------[0m
[2018-06-20 12:18:02.879] [d-48VU0RRTT][stdout]# Declared in /var/chef/cache/cookbooks/code_deploy/recipes/default.rb:1:in `from_file'
[2018-06-20 12:18:02.879] [d-48VU0RRTT][stdout][0m
[2018-06-20 12:18:02.879] [d-48VU0RRTT][stdout][0mcode_deploy_agent("codedeploy-agent") do
[2018-06-20 12:18:02.879] [d-48VU0RRTT][stdout][0m action [:install, :enable, :start]
[2018-06-20 12:18:02.879] [d-48VU0RRTT][stdout][0m updated true
[2018-06-20 12:18:02.879] [d-48VU0RRTT][stdout][0m updated_by_last_action true
[2018-06-20 12:18:02.879] [d-48VU0RRTT][stdout][0m retries 0
[2018-06-20 12:18:02.879] [d-48VU0RRTT][stdout][0m retry_delay 2
[2018-06-20 12:18:02.879] [d-48VU0RRTT][stdout][0m default_guard_interpreter :default
[2018-06-20 12:18:02.879] [d-48VU0RRTT][stdout][0m declared_type :code_deploy_agent
[2018-06-20 12:18:02.879] [d-48VU0RRTT][stdout][0m cookbook_name "code_deploy"
[2018-06-20 12:18:02.879] [d-48VU0RRTT][stdout][0m recipe_name "default"
[2018-06-20 12:18:02.879] [d-48VU0RRTT][stdout][0mend
[2018-06-20 12:18:02.880] [d-48VU0RRTT][stdout][0m
[2018-06-20 12:18:02.880] [d-48VU0RRTT][stdout][0mPlatform:[0m
[2018-06-20 12:18:02.880] [d-48VU0RRTT][stdout]---------[0m
[2018-06-20 12:18:02.880] [d-48VU0RRTT][stdout]x86_64-linux[0m
[2018-06-20 12:18:02.880] [d-48VU0RRTT][stdout]
[2018-06-20 12:18:02.880] [d-48VU0RRTT][stdout][0m[2018-06-20T12:18:02-04:00] INFO: Running queued delayed notifications before re-raising exception
[2018-06-20 12:18:02.882] [d-48VU0RRTT][stdout][2018-06-20T12:18:02-04:00] ERROR: Running exception handlers
[2018-06-20 12:18:02.882] [d-48VU0RRTT][stdout][2018-06-20T12:18:02-04:00] ERROR: Exception handlers complete
[2018-06-20 12:18:02.885] [d-48VU0RRTT][stdout][2018-06-20T12:18:02-04:00] INFO: Sending resource update report (run-id: 76d25a70-80ed-4a53-a9e1-1196c8bc8ac3)
[2018-06-20 12:18:03.231] [d-48VU0RRTT][stdout][2018-06-20T12:18:03-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2018-06-20 12:18:03.231] [d-48VU0RRTT][stdout][2018-06-20T12:18:03-04:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-06-20 12:18:03.231] [d-48VU0RRTT][stdout][2018-06-20T12:18:03-04:00] ERROR: code_deploy_agent[codedeploy-agent] (code_deploy::default line 1) had an error: Mixlib::ShellOut::CommandTimeout: yum_package[/var/chef/cache/code_deploy/codedeploy-agent-1.0-1.1518.noarch.rpm] (/var/chef/cache/cookbooks/code_deploy/resources/agent_rhel.rb line 19) had an error: Mixlib::ShellOut::CommandTimeout: Command timed out after 900s:
[2018-06-20 12:18:03.231] [d-48VU0RRTT][stdout]Command exceeded allowed execution time, process terminated
[2018-06-20 12:18:03.231] [d-48VU0RRTT][stdout]---- Begin output of yum -d0 -e0 -y localinstall /var/chef/cache/code_deploy/codedeploy-agent-1.0-1.1518.noarch.rpm ----
[2018-06-20 12:18:03.231] [d-48VU0RRTT][stdout]STDOUT: pre hook : 2
[2018-06-20 12:18:03.231] [d-48VU0RRTT][stdout]Checking the ruby version.
[2018-06-20 12:18:03.231] [d-48VU0RRTT][stdout]Stop the running codedeploy-agent in the pre hook.
[2018-06-20 12:18:03.231] [d-48VU0RRTT][stdout]Stopping codedeploy-agent:error: %pre(codedeploy-agent-1.0-1.1518.noarch) scriptlet failed, signal 15
[2018-06-20 12:18:03.232] [d-48VU0RRTT][stdout]STDERR: Error in PREIN scriptlet in rpm package codedeploy-agent-1.0-1.1518.noarch
[2018-06-20 12:18:03.232] [d-48VU0RRTT][stdout]---- End output of yum -d0 -e0 -y localinstall /var/chef/cache/code_deploy/codedeploy-agent-1.0-1.1518.noarch.rpm ----
[2018-06-20 12:18:03.232] [d-48VU0RRTT][stdout]Ran yum -d0 -e0 -y localinstall /var/chef/cache/code_deploy/codedeploy-agent-1.0-1.1518.noarch.rpm returned 1
[2018-06-20 12:18:03.541] [d-48VU0RRTT][stdout][2018-06-20T12:18:03-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)```

**Comment by meringu** [comment]
Looks like it might be failing to stop the agent. Are there any errors in the codedeploy agent logs?

**Comment by meringu** [comment]
Is the chef run happening inside the CodeDeploy deployment? I can see what looks like a deployment id in the log lines. That could be why it is failing to stop the agent. Perhaps it blocks, waiting for the deployment to finish?

**Comment by vijaypatnana** [comment]
Yes, we have specified the deployment cookbooks at the beginning of the run list. in the end, we have code_deploy cookbook. Why is it trying to stop the agent here?. The agent is already installed and up and running. Here we are using codedeploy to trigger the chef-client, the deployment is completed but, codedeploy cookbook is failing at the end.

**Comment by meringu** [comment]
Because this cookbook installs the latest version of the agent. When an update is available, the RPM package stops the old version, installs the new version, then starts the new version.

As such, running this cook book should happen out of band of a CodeDeploy deployment.

For example, your deployment could just register your node with chef server and configure chef client to run periodically. Instead of running during the deployment.

**Comment by vijaypatnana** [comment]
Yes, you are right! we need to keep this infrastructure changes in separate role file. Thanks for the pointers.
